language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

# https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
sudo: required
dist: xenial

services:
  - xvfb

install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq xclip gnupg2"
  - "pip install --upgrade -r .travis-requirements.txt"
  - "pip install -e ."

script: PW_GPG=gpg2 make test
