language: python
python:
  - "3.4"
  - "3.5"

install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq xclip gnupg2"
  - "pip install --upgrade -r .travis-requirements.txt"
  - "pip install -e ."

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"

script: make test
