language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

# https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
sudo: required
dist: xenial

install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq xclip gnupg2"
  - "pip install --upgrade -r .travis-requirements.txt"
  - "pip install -e ."

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"

script: make test
