language: python
python:
  - "2.7"
  - "pypy"
  # "3.4" currently fails due to pypi's xerox being outdated

install:
  - pip install -r .travis-requirements.txt
  - pip install --editable .

script: make test
