language: python
python:
  - "3.9"
  - "3.10"
  - "3.11"

# https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
sudo: required
dist: xenial

services:
  - xvfb

install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq xclip gnupg2"
  - travis_retry pip install poetry
  - travis_retry poetry install

script: PW_GPG=gpg2 make test
